In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set(style="darkgrid")
import torch
import torch.nn as nn
import ConfigSpace as CS

In [2]:
a1 = [1, 2, 3, 4, 5]
a2 = [1.1, 2.1, 3.1, 4.5, 5.1]
a3 = [0.8, 1.8, 2.6, 3.78, 4.9]
a4 = [1, 2, 3, 4, 5]

b1 = a1[::-1]
b2 = a2[::-1]
b3 = a3[::-1]
b4 = a4[::-1]

In [18]:
df = pd.DataFrame({'train': a1, 'test' : b1})
df = df.append(pd.Series([1, 2], index=df.columns), ignore_index=True)
df

train  test
0      1     5
1      2     4
2      3     3
3      4     2
4      5     1
5      1     2

In [9]:
# sns.relplot(x="timepoint", y="signal", kind="line", data=fmri);
fmri = sns.load_dataset("fmri")
fmri

subject  timepoint event    region    signal
0        s13         18  stim  parietal -0.017552
1         s5         14  stim  parietal -0.080883
2        s12         18  stim  parietal -0.081033
3        s11         18  stim  parietal -0.046134
4        s10         18  stim  parietal -0.037970
...      ...        ...   ...       ...       ...
1059      s0          8   cue   frontal  0.018165
1060     s13          7   cue   frontal -0.029130
1061     s12          7   cue   frontal -0.004939
1062     s11          7   cue   frontal -0.025367
1063      s0          0   cue  parietal -0.006899

[1064 rows x 5 columns]

In [21]:
columns = ['Epoch', 'Loss', 'Run Type']
df = pd.DataFrame(columns=columns)
df = df.append(pd.Series([1, 2, 3], index=df.columns), ignore_index=True)
df

Epoch Loss Run Type
0     1    2        3

In [12]:
def expo_loss(prediction, target):
    scale = prediction
    log_scale = torch.log(scale)
    nll = log_scale - scale*target
    return -nll

In [ ]:
def expo_loss(prediction, target):
    scale = prediction
    log_scale = torch.log(scale)
    nll = log_scale - scale*target
    return -nll

In [13]:
prediction = torch.tensor([1.0,2.0,3.0,4.0])
target = torch.tensor([1.0,1.0,1.0,1.0])
expo_loss(prediction, target)

tensor([1.0000, 1.3069, 1.9014, 2.6137])

In [28]:
prediction = torch.tensor([[1.0,2.0],[2.0,3.0], [3.0, 4.0]])
target = torch.tensor([[1.0,0.5],[1.0,0.5], [1.0, 0.5]])

In [38]:
print(prediction)
print(prediction[:,1:2])
print(prediction[:,1:2]**2)
print(prediction+0.01)
print(torch.sum(prediction).item())
print(prediction)
print(torch.max(prediction))
print(prediction + 1)

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])
tensor([[2.],
        [3.],
        [4.]])
tensor([[ 4.],
        [ 9.],
        [16.]])
tensor([[1.0100, 2.0100],
        [2.0100, 3.0100],
        [3.0100, 4.0100]])
15.0
tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])
tensor(4.)
tensor([[2., 3.],
        [3., 4.],
        [4., 5.]])


In [41]:
t = torch.zeros((prediction.shape[0]))
print(t)
print(torch.mean(t))

tensor([0., 0., 0.])
tensor(0.)


In [45]:
for i in prediction[:,1]:
    print(i.item())

2.0
3.0
4.0


In [46]:
cs = CS.ConfigurationSpace()
cs.add_hyperparameter(alpha)

In [66]:
prediction = torch.tensor([[1.0,2.0],[2.0,3.0], [3.0, 4.0]])
prediction

tensor([[1., 2.],
        [2., 3.],
        [3., 4.]])

In [1]:
torch.log_(prediction[:,0])
print(prediction)
print(prediction.shape[1] == 2)
print(len(prediction.shape))

NameError: name 'torch' is not defined

In [6]:
data = torch.tensor([1,2,3,4,5])
m = torch.tensor([1,0,0,1,0])
mask = m == 1
print(mask)
print(data[mask])
print(data[~mask])

tensor([ True, False, False,  True, False])
tensor([1, 4])
tensor([2, 3, 5])


In [8]:
1 - data

tensor([ 0, -1, -2, -3, -4])

In [17]:
mus = torch.Tensor([[1, 1, 1, 0.75, 0.75, 0.75]])
sigmas = torch.Tensor([[0.5, 0.5, 0.5, 3, 3, 3]])
torch.t(torch.cat((mus, sigmas), 0))

tensor([[1.0000, 0.5000],
        [1.0000, 0.5000],
        [1.0000, 0.5000],
        [0.7500, 3.0000],
        [0.7500, 3.0000],
        [0.7500, 3.0000]])